Mufti-Dev/Haytham

Slice_From_STLContainer/Slice_From_STLContainer/Slice_From_STLContainer.cpp
Made more compact function and leveraged ranged based constructor for containers.
=> Updated for std::list

.gitignore, Find_common_Elmnts/Find_common_Elmnts/Find_common_Elmnts.cpp
Finding common elements between two vectors.
=> Common elements between two vectors

.gitignore, decltype_auto/decltype_auto/decltype_auto.cpp
A simple demo to show a function return type changes based on input type it operates on.
=> A simple demo on decltype (auto) as function return type

BST_Impl/BST_Impl.cpp
Update for inorder successor for BST
=> Update for inorder successor for BST

.gitignore, Practice/Queue_Implementation/QueueImplClass.cpp, Practice/Queue_Implementation/QueueImplClass.h, Practice/Queue_Implementation/Queue_Implementation.cpp, Practice/STL_Queue_Usage/STL_Queue_Usage.cpp
1. A queue implementation (Array Based)
2. Generate all binary number between [1...N] using a queue
=> Queue implementation - Array based

Conversion/getNumberOfDigitsInDecimalNumber.cpp
No modulo and division operation required.
=> Number of digits in a decimal number

Conversion/extractDecimalAndIntegerPartOfANumber.cpp
Using math library modf() / modff() function. It is available in C++ 11 onwards
=> Extract decimal and integer part of any number 

Array_Arrangement/MinMaxArrangement_O(N)_Space.cpp
Example: Input Array=abcdefgh and output= hagbfced. Using O(N) space and O(N) time complexity
=> Arrange a sorted array in Max/Min order

Array_Arrangement/MinMaxArrangement_O(1)_Space.cpp
Using O(1) extra space and O(N) time complexity
=> Arrange a sorted array(integer) into Max/Min form

Array_Arrangement/ReverseAnIntegerArrayWithoutSwapping_O(1).txt
O(1) space used and O(n) time complexity
=> Reverse a sorted integer array without swapping its elements

Array_Arrangement/ReverseWordsInASentence.cpp
1. O(1) space complexity implementation
2. O(N) space and time complexity
=> Reverse words in a sentence

Array_Arrangement/FindTwoNumbersFromArray_SumEqualsToX.cpp
1. Used sort and two pointer method (sort: O(NlogN) and space O(1))
2. Used hash technique: O(N) and space O(N)
=> From an array of integer find two numbers whose sum equals supplied number X

Conversion/romanNumeralsToNumber_viceversa.cpp
1. Function to add roman numerals to number (int)
=> converts roman numerals to number

Conversion/romanNumeralsToNumber_viceversa.cpp
Converts Roman numerals to int and vice versa
=> Roman numerals to integer and vice versa

Sorting_Data/Roman_numerals_sorting_By_Its_Value.cpp
Array of roman numerals sorting by its value
=> All about sorting

Conversion_routines/phoneNumberToMnemonics.cpp
=> A routine to convert phone number to mnemonics

Queue/Queue_Implementation_Using_Stack.cpp
Queue Implementation using std::stack
=> Queue implementation by stack

C++_Internals/vtable_Simulation.cpp
=> C++_Internals

Queue/sorting_StringByCharsFrequency.txt
1. std::priority_queue used with a lambda compare function
=> sorting chars in a string by occurrence frequencies

Strings/maxLength_Substring_Withour_RepeatingChars.cpp
Get length of sub string from a supplied string, which has no repeating characters .
=> String manipulation

C++_In_Depth/bit_Stream_alternate_pattern.cpp
Bit streams alternate pattern checker
=> Check underlying bit stream has alternating pattern

Windows_Internals/GetMACAddress/Mac_Address.cpp, Windows_Internals/GetMACAddress/stdafx.cpp, Windows_Internals/GetMACAddress/stdafx.h, Windows_Internals/GetMACAddress/targetver.h
Get mac address of a windows host
=> Get MAC address of a system running Windows OS

DirectShow - Windows Audio Video programming/MyPlayer/MyPlayer.cpp, DirectShow - Windows Audio Video programming/MyPlayer/stdafx.cpp, DirectShow - Windows Audio Video programming/MyPlayer/stdafx.h
A simple Win32 video player program which plays video using underlying Direct Show filter graph
=> A simple video player

DirectShow - Windows Audio Video programming/ASF_File Indexer/Indexer.cpp
Just a sample effort for indexing ASF file
=> ASF indexing application program

Windows_System_Programming/Disable_Network_Interface_Card/DisableNIC.cpp
A console based program which disables network interface card on windows host. Windows socket library used
=> Disable Network Interface Card on Windows Host

C++_In_Depth/find_Object_By_Attribute.cpp
Find an object from a vector of objects by attribute
=> Find object by attribute

C++_In_Depth/An_Array_Management_class.cpp
Just a basic array management class
=> A basic array management class
